version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - my-network
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
